### ISSUE TITLE
Error when using maxItems

### ISSUE THREAD

**Issue by Janpot** [hans-d/node-stream-batch#1]
Trying to use this with:

``` js
process.stdin
  .pipe(split(/\s+/))
  .pipe(batch({ maxItems: 1000 }))
```

But I get an exception

```
/node_modules/stream-batch/dist/index.js:28
    if (opts.maxItems && batch.length >= opts.maxItems) {
                         ^
ReferenceError: batch is not defined
    at DestroyableTransform.bufferIt [as _transform] (/node_modules/stream-batch/dist/index.js:28:26)
    at DestroyableTransform.Transform._read (/node_modules/stream-batch/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/node_modules/stream-batch/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/node_modules/stream-batch/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/node_modules/stream-batch/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/node_modules/stream-batch/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:117:20)
    at drain (/node_modules/split/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/node_modules/split/node_modules/through/index.js:45:5)
```

**Comment by hans-d** [comment]
Thanks for reporting. Should be fixed now.

**Comment by aredridel** [comment]
Want to publish a fixed version?

**Comment by hans-d** [comment]
sorry for that, should now be fixed.
